import type { Metadata } from 'next';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import SiteInteractions from '@/components/SiteInteractions';

export const metadata: Metadata = {
  title: 'KYC e PLD/FT para cooperativas de crédito · Circular BCB 3.978 | kycert',
  description:
    'Verificação e monitoramento do quadro de associados sob a Circular BCB 3.978/2020, com trilha auditável para o Banco Central.',
  alternates: { canonical: '/solucoes/cooperativas' },
  openGraph: {
    title: 'KYC e PLD/FT para cooperativas de crédito · Circular BCB 3.978 | kycert',
    description:
      'Verificação e monitoramento do quadro de associados sob a Circular BCB 3.978/2020, com trilha auditável para o Banco Central.',
  },
  twitter: {
    title: 'KYC e PLD/FT para cooperativas de crédito · Circular BCB 3.978 | kycert',
    description:
      'Verificação e monitoramento do quadro de associados sob a Circular BCB 3.978/2020, com trilha auditável para o Banco Central.',
  },
};

const JSONLD = `{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Início","item":"https://kycert.com.br/"},{"@type":"ListItem","position":2,"name":"Soluções"},{"@type":"ListItem","position":3,"name":"Cooperativas de crédito"}]}`;

const BODY_HTML = `
<nav class="crumbs"><div class="wrap"><a href="/">Início</a><span class="sep">/</span><span>Soluções</span><span class="sep">/</span><span style="color:var(--text-secondary)">Cooperativas de crédito</span></div></nav>
<div class="wrap hero"><div class="hero-grid"><div>
<span class="seg-pill reveal"><span class="dot"></span>Para cooperativas de crédito</span>
<h1 class="reveal reveal-d1">O associado é cliente. <span class="em">Cada adesão, um cadastro de PLD/FT.</span></h1>
<p class="lead reveal reveal-d2">Cooperativas de crédito integram o SFN e respondem à Circular BCB 3.978/2020 como qualquer instituição autorizada. A kycert verifica o associado na adesão e monitora o cadastro ao longo do relacionamento.</p>
<div class="cta reveal reveal-d3"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-primary btn-lg" target="_blank" rel="noopener">Agendar demo <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a><a href="/dossie-exemplo" class="btn btn-ghost btn-lg">Ver dossiê de exemplo</a></div>
</div><div class="hero-visual reveal reveal-d2"><div class="ui-card"><div class="ui-head"><span class="t"><span class="live-dot"></span> Associado · adesão</span><span class="badge">KYC</span></div><div class="ui-row seq"><span class="lbl"><b>Identidade</b> · documento por OCR</span><span class="st">Verificado</span></div><div class="ui-row seq"><span class="lbl"><b>Situação cadastral</b> · Receita</span><span class="st">Regular</span></div><div class="ui-row seq"><span class="lbl"><b>Sanções & PEP</b> · OFAC e listas</span><span class="st">Sem ocorrência</span></div><div class="ui-row seq"><span class="lbl"><b>Cadastro</b> · vencimento controlado</span><span class="st">Registrado</span></div><div class="ui-foot"><span>Trilha pronta para o BCB</span><span class="mono">Trilha cooperativa</span></div></div></div></div></div>
<div class="marquee-wrap"><div class="wrap" style="display:flex;align-items:center;gap:18px;justify-content:center;flex-wrap:wrap"><span class="marquee-lab" style="margin:0">Base regulatória</span><span class="stag"><span class="gd"></span>Circular BCB 3.978/2020</span><span class="stag"><span class="gd"></span>Lei 9.613/98</span><span class="stag"><span class="gd"></span>COAF</span><span class="stag"><span class="gd"></span>LGPD</span></div></div>
<section><div class="wrap sec-head"><span class="eyebrow reveal">O dia a dia hoje</span><h2 class="reveal reveal-d1">Onde o quadro de associados pesa.</h2><p class="sec-lead reveal reveal-d2">Admitir, qualificar e monitorar associados com os mesmos deveres de um banco.</p><div class="pain-grid"><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/></svg></span><h3>Adesão é abertura de relacionamento</h3></div><p>A entrada de um associado equivale, para PLD, a abrir conta: identificação, listas restritivas e avaliação de risco.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> adesão sem verificação é risco no SFN</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></span><h3>A obrigação continua depois da adesão</h3></div><p>A Circular 3.978 pede acompanhamento ao longo do relacionamento, com reverificação no vencimento.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> cadastro vencido segue ativo</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 3v5h5M7 3h8l5 5v13H7z"/></svg></span><h3>Controle manual não escala</h3></div><p>Planilha e memória não dão conta de centenas ou milhares de associados.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> gargalo ou atalho que deixa risco passar</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 9v4M12 17h.01"/><path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/></svg></span><h3>Fiscalização do BCB</h3></div><p>A cooperativa precisa demonstrar a trilha de cada associado quando solicitada.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> evidência reconstruída não se sustenta</div></div></div></div></section>
<section class="sec-soft"><div class="wrap sec-head"><span class="eyebrow reveal">Como a kycert resolve</span><h2 class="reveal reveal-d1">Da adesão ao monitoramento.</h2><div class="solmap"><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Adesão de associado com deveres de PLD iguais aos de um banco.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Verificação na adesão.</b> Identidade, situação cadastral, sanções e PEP no cadastro, com avaliação de risco registrada.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Monitoramento contínuo exigido pela 3.978.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Reverificação no prazo.</b> A plataforma controla o vencimento de cada cadastro e dispara a revisão automaticamente.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Controle manual que não escala.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Fluxo padronizado.</b> Todo o quadro de associados verificado pelo mesmo processo, com trilha por pessoa.</p></div></div></div></div></section>
<section><div class="wrap sec-head"><span class="eyebrow reveal">Da regra à operação</span><h2 class="reveal reveal-d1">O que a regulação pede, e onde a kycert entra.</h2><div class="norms"><div class="norm reveal"><div class="nlaw">Circular BCB nº 3.978/2020</div><p>PLD/FT para instituições autorizadas: identificação, qualificação e monitoramento do cliente.</p><div class="entra"><b>Onde a kycert entra</b>Verificação do associado, enquadramento de risco e ficha auditável.</div></div><div class="norm reveal"><div class="nlaw">Lei nº 9.613/98 + COAF</div><p>Deveres de prevenção e comunicação de operações suspeitas.</p><div class="entra"><b>Onde a kycert entra</b>Listas restritivas no fluxo e evidência da decisão.</div></div><div class="norm reveal"><div class="nlaw">LGPD · Lei nº 13.709/18</div><p>Tratamento de dados dos associados com base legal e controles.</p><div class="entra"><b>Onde a kycert entra</b>Registros de tratamento e controle de acesso.</div></div></div><p class="fineprint reveal">A kycert estrutura e registra o onboarding; não substitui assessoria jurídica nem dispensa os demais deveres do regulado.</p></div></section>
<section style="padding:64px 0 88px" id="demo"><div class="wrap"><div class="band reveal"><span class="eyebrow on-dark" style="justify-content:center">kycert para cooperativas de crédito</span><h2 class="serif">Verifique o quadro de associados com trilha.</h2><p>Veja a verificação e o monitoramento de associados, em 30 minutos.</p><div class="cta"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-on-dark btn-lg" target="_blank" rel="noopener">Agendar demo</a><a href="/dossie-exemplo" class="btn btn-ghost-dark btn-lg">Ver dossiê de exemplo</a></div></div></div></section>
`;

export default function Page() {
  return (
    <>
      <Nav active="solucoes" />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSONLD }} />
      <div dangerouslySetInnerHTML={{ __html: BODY_HTML }} />
      <Footer />
      <SiteInteractions />
    </>
  );
}
