import type { Metadata } from 'next';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import { BreadcrumbJsonLd } from '@/components/BreadcrumbJsonLd';
import SiteInteractions from '@/components/SiteInteractions';

export const metadata: Metadata = {
  title: 'KYC e PLD/FT para seguradoras sob a SUSEP',
  description:
    'Identificação do segurado, contratante PJ e beneficiário final, com avaliação de risco e trilha auditável sob a supervisão da SUSEP.',
  alternates: { canonical: '/solucoes/seguradoras' },
  openGraph: {
    title: 'KYC e PLD/FT para seguradoras sob a SUSEP | kycert',
    description:
      'Identificação do segurado, contratante PJ e beneficiário final, com avaliação de risco e trilha auditável sob a supervisão da SUSEP.',
  },
  twitter: {
    title: 'KYC e PLD/FT para seguradoras sob a SUSEP | kycert',
    description:
      'Identificação do segurado, contratante PJ e beneficiário final, com avaliação de risco e trilha auditável sob a supervisão da SUSEP.',
  },
};


const BREADCRUMB_ITEMS = [{"name":"Início","path":"/"},{"name":"Seguradoras"}];

const BODY_HTML = `
<nav class="crumbs"><div class="wrap"><a href="/">Início</a><span class="sep">/</span><span>Soluções</span><span class="sep">/</span><span style="color:var(--text-secondary)">Seguradoras</span></div></nav>
<div class="wrap hero"><div class="hero-grid"><div>
<span class="seg-pill reveal"><span class="dot"></span>Para seguradoras e corretoras</span>
<h1 class="reveal reveal-d1">Conheça o segurado. <span class="em">Registre a avaliação de risco.</span></h1>
<p class="lead reveal reveal-d2">O setor de seguros é entidade obrigada em PLD/FT, sob supervisão da SUSEP. A kycert estrutura o cadastro do segurado e do contratante PJ e registra a avaliação de risco como evidência.</p>
<div class="cta reveal reveal-d3"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-primary btn-lg" target="_blank" rel="noopener">Agendar demo <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a><a href="/dossie-exemplo" class="btn btn-ghost btn-lg">Ver dossiê de exemplo</a></div>
</div><div class="hero-visual reveal reveal-d2"><div class="ui-card"><div class="ui-head"><span class="t"><span class="live-dot"></span> Segurado · contratação</span><span class="badge">PLD</span></div><div class="ui-row seq"><span class="lbl"><b>Identidade</b> · documento por OCR</span><span class="st">Verificado</span></div><div class="ui-row seq"><span class="lbl"><b>Situação cadastral</b> · Receita</span><span class="st">Regular</span></div><div class="ui-row seq"><span class="lbl"><b>Sanções & PEP</b> · OFAC e listas</span><span class="st">Sem ocorrência</span></div><div class="ui-row seq"><span class="lbl"><b>Risco</b> · avaliação registrada</span><span class="st warn">Médio · revisar</span></div><div class="ui-foot"><span>Avaliação pronta para a SUSEP</span><span class="mono">Trilha seguros</span></div></div></div></div></div>
<div class="marquee-wrap"><div class="wrap" style="display:flex;align-items:center;gap:18px;justify-content:center;flex-wrap:wrap"><span class="marquee-lab" style="margin:0">Base regulatória</span><span class="stag"><span class="gd"></span>Circular SUSEP 612/2020</span><span class="stag"><span class="gd"></span>Lei 9.613/98</span><span class="stag"><span class="gd"></span>COAF</span><span class="stag"><span class="gd"></span>LGPD</span></div></div>
<section><div class="wrap sec-head"><span class="eyebrow reveal">O dia a dia hoje</span><h2 class="reveal reveal-d1">Onde o cadastro do segurado trava.</h2><p class="sec-lead reveal reveal-d2">Vida, capitalização e apólices PJ trazem deveres de identificação e avaliação de risco.</p><div class="pain-grid"><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/></svg></span><h3>Conhecer quem contrata</h3></div><p>A contratação, sobretudo em vida e capitalização, exige identificar e qualificar o segurado, com registro da avaliação de risco.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> avaliação sem registro não conta</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2l8 4v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6z"/></svg></span><h3>Beneficiários e PJ ampliam o escopo</h3></div><p>Apólices com beneficiários e contratantes PJ exigem chegar ao beneficiário final da relação.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> risco mora em quem se beneficia</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 9v4M12 17h.01"/><path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/></svg></span><h3>PLD sob a SUSEP</h3></div><p>A seguradora responde a deveres de prevenção que precisam estar documentados para a fiscalização.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> trilha espalhada não comprova</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></span><h3>Cadastro que envelhece</h3></div><p>O perfil de risco do segurado muda; sem revisão periódica, o cadastro fica defasado.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> cadastro vencido é exposição aberta</div></div></div></div></section>
<section class="sec-soft"><div class="wrap sec-head"><span class="eyebrow reveal">Como a kycert resolve</span><h2 class="reveal reveal-d1">Do contrato à evidência.</h2><div class="solmap"><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Identificação e qualificação do segurado, com avaliação de risco.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Cadastro estruturado.</b> Identidade, situação cadastral, sanções e PEP verificados, com a avaliação de risco registrada.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Apólices com beneficiários e contratantes PJ.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>KYB com beneficiário final.</b> Quadro societário do contratante PJ recuperado e cada entidade verificada até o controlador.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>PLD sob a SUSEP, sem trilha consolidada.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Decisão registrada.</b> Autor, data e critério de cada avaliação ficam na ficha, prontos para a SUSEP e o COAF.</p></div></div></div></div></section>
<section><div class="wrap sec-head"><span class="eyebrow reveal">Da regra à operação</span><h2 class="reveal reveal-d1">O que a regulação pede, e onde a kycert entra.</h2><div class="norms"><div class="norm reveal"><div class="nlaw">Circular SUSEP nº 612/2020</div><p>Estabelecem os controles de prevenção à lavagem aplicáveis a seguradoras, resseguradoras e corretoras.</p><div class="entra"><b>Onde a kycert entra</b>Cadastro do segurado, avaliação de risco e evidência da decisão.</div></div><div class="norm reveal"><div class="nlaw">Lei nº 9.613/98 + COAF</div><p>Deveres de identificação, registro e comunicação de operações.</p><div class="entra"><b>Onde a kycert entra</b>Listas restritivas no fluxo e ficha auditável por cliente.</div></div><div class="norm reveal"><div class="nlaw">LGPD · Lei nº 13.709/18</div><p>Tratamento de dados pessoais com base legal e controles.</p><div class="entra"><b>Onde a kycert entra</b>Operadora de dados com registros de tratamento e controle de acesso.</div></div></div><p class="fineprint reveal">A kycert estrutura e registra o onboarding; não substitui assessoria jurídica nem dispensa os demais deveres do regulado.</p></div></section>
<section style="padding:64px 0 88px" id="demo"><div class="wrap"><div class="band reveal"><span class="eyebrow on-dark" style="justify-content:center">kycert para seguradoras</span><h2 class="serif">Sua trilha de PLD pronta para a SUSEP.</h2><p>Veja o cadastro do segurado com avaliação de risco registrada, em 30 minutos.</p><div class="cta"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-on-dark btn-lg" target="_blank" rel="noopener">Agendar demo</a><a href="/dossie-exemplo" class="btn btn-ghost-dark btn-lg">Ver dossiê de exemplo</a></div></div></div></section>
`;

export default function Page() {
  return (
    <>
      <Nav active="solucoes" />
      <BreadcrumbJsonLd items={BREADCRUMB_ITEMS} />
      <div dangerouslySetInnerHTML={{ __html: BODY_HTML }} />
      <Footer />
      <SiteInteractions />
    </>
  );
}
