import type { Metadata } from 'next';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import SiteInteractions from '@/components/SiteInteractions';

export const metadata: Metadata = {
  title: 'KYC e PLD para casas de apostas (Bets) · Lei 14.790/2023 | kycert',
  description:
    'Identificação do apostador, idade, sanções, PEP e PLD/FT para casas de apostas reguladas pela SPA/MF sob a Lei 14.790/2023.',
  alternates: { canonical: '/solucoes/bets' },
  openGraph: {
    title: 'KYC e PLD para casas de apostas (Bets) · Lei 14.790/2023 | kycert',
    description:
      'Identificação do apostador, idade, sanções, PEP e PLD/FT para casas de apostas reguladas pela SPA/MF sob a Lei 14.790/2023.',
  },
  twitter: {
    title: 'KYC e PLD para casas de apostas (Bets) · Lei 14.790/2023 | kycert',
    description:
      'Identificação do apostador, idade, sanções, PEP e PLD/FT para casas de apostas reguladas pela SPA/MF sob a Lei 14.790/2023.',
  },
};

const JSONLD = `{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Início","item":"https://kycert.com.br/"},{"@type":"ListItem","position":2,"name":"Soluções"},{"@type":"ListItem","position":3,"name":"Apostas / Bets"}]}`;

const BODY_HTML = `
<nav class="crumbs"><div class="wrap"><a href="/">Início</a><span class="sep">/</span><span>Soluções</span><span class="sep">/</span><span style="color:var(--text-secondary)">Apostas / Bets</span></div></nav>
<div class="wrap hero"><div class="hero-grid"><div>
<span class="seg-pill reveal"><span class="dot"></span>Para casas de apostas</span>
<h1 class="reveal reveal-d1">A casa virou entidade obrigada. <span class="em">Cada apostador, um cliente de PLD.</span></h1>
<p class="lead reveal reveal-d2">A Lei 14.790/2023 e a regulamentação da SPA/MF trouxeram identificação obrigatória do apostador e deveres de PLD/FT. A kycert verifica cada apostador no cadastro e registra a decisão como evidência auditável.</p>
<div class="cta reveal reveal-d3"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-primary btn-lg" target="_blank" rel="noopener">Agendar demo <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a><a href="/dossie-exemplo" class="btn btn-ghost btn-lg">Ver dossiê de exemplo</a></div>
</div><div class="hero-visual reveal reveal-d2"><div class="ui-card"><div class="ui-head"><span class="t"><span class="live-dot"></span> Apostador · pessoa física</span><span class="badge">KYC</span></div><div class="ui-row seq"><span class="lbl"><b>Identidade</b> · documento por OCR</span><span class="st">Verificado</span></div><div class="ui-row seq"><span class="lbl"><b>Idade</b> · maior de 18</span><span class="st">Confirmada</span></div><div class="ui-row seq"><span class="lbl"><b>Sanções & PEP</b> · OFAC e listas</span><span class="st">Sem ocorrência</span></div><div class="ui-row seq"><span class="lbl"><b>Conta gráfica</b> · nominal e liberada</span><span class="st">Registrado</span></div><div class="ui-row seq"><span class="lbl"><b>Biometria facial</b> · prova de vida</span><span class="st" style="color:var(--text-tertiary)">Em breve</span></div><div class="ui-foot"><span>Cada etapa registrada para a SPA/MF</span><span class="mono">Trilha Bets</span></div></div></div></div></div>
<div class="marquee-wrap"><div class="wrap" style="display:flex;align-items:center;gap:18px;justify-content:center;flex-wrap:wrap"><span class="marquee-lab" style="margin:0">Base regulatória</span><span class="stag"><span class="gd"></span>Lei 14.790/2023</span><span class="stag"><span class="gd"></span>Portarias SPA/MF 722 e 827/2024</span><span class="stag"><span class="gd"></span>Lei 9.613/98</span><span class="stag"><span class="gd"></span>COAF</span><span class="stag"><span class="gd"></span>LGPD</span></div></div>
<section><div class="wrap sec-head"><span class="eyebrow reveal">O dia a dia hoje</span><h2 class="reveal reveal-d1">Onde o onboarding de apostas aperta.</h2><p class="sec-lead reveal reveal-d2">Alto volume, cliente impaciente e um regulador novo cobrando identificação e PLD.</p><div class="pain-grid"><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/></svg></span><h3>Identificação que virou lei</h3></div><p>Cada apostador precisa ser identificado por documento e CPF, com idade confirmada, antes da primeira aposta — em conta nominal e intransferível.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> cadastro sem verificação é risco de autorização</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M13 2L3 14h7l-1 8 10-12h-7z"/></svg></span><h3>Volume alto, paciência baixa</h3></div><p>O apostador abandona um cadastro lento. É preciso verificar identidade, idade, sanções e PEP em segundos.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> onboarding lento afasta o apostador legítimo</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 9v4M12 17h.01"/><path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/></svg></span><h3>O PLD/FT agora vale para apostas</h3></div><p>A casa passou a ser entidade obrigada: avaliação de risco, listas restritivas e comunicação ao COAF.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> sem trilha não há como comprovar PLD</div></div><div class="pain reveal"><div class="ph"><span class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 3v5h5M7 3h8l5 5v13H7z"/></svg></span><h3>Fiscalização da SPA/MF</h3></div><p>O regulador pode pedir a trilha de qualquer apostador. Reconstruir a partir de logs soltos não se sustenta.</p><div class="cost"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> evidência espalhada não comprova</div></div></div></div></section>
<section class="sec-soft"><div class="wrap sec-head"><span class="eyebrow reveal">Como a kycert resolve</span><h2 class="reveal reveal-d1">Cada dor vira um passo do fluxo.</h2><div class="solmap"><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Identificação obrigatória do apostador, com idade e conta nominal.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>KYC no cadastro.</b> Documento por OCR, idade confirmada, CPF validado e cruzamento com sanções e PEP antes da primeira aposta.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>Volume alto de apostadores que abandonam cadastro lento.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Verificação em segundos.</b> Fontes consultadas em bloco, com captura por câmera — rápido para o apostador, completo para a casa.</p></div></div><div class="solrow reveal"><div class="from"><div class="l"><span style="width:6px;height:6px;border-radius:50%;background:#C0392B;display:inline-block"></span>A dor</div><p>PLD/FT exigido sem trilha para comprovar.</p></div><div class="arrow"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></div><div class="to"><div class="l"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 12l5 5L20 7"/></svg> Na kycert</div><p><b>Decisão registrada.</b> Avaliação de risco do apostador gravada com autor, data e critério, pronta para a SPA/MF e o COAF.</p></div></div></div></div></section>
<section><div class="wrap sec-head"><span class="eyebrow reveal">Da regra à operação</span><h2 class="reveal reveal-d1">O que a regulação pede, e onde a kycert entra.</h2><div class="norms"><div class="norm reveal"><div class="nlaw">Lei nº 14.790/2023</div><p>Regulamenta as apostas de quota fixa e as obrigações das operadoras autorizadas.</p><div class="entra"><b>Onde a kycert entra</b>Identificação do apostador, idade e trilha da decisão de cadastro.</div></div><div class="norm reveal"><div class="nlaw">Portaria SPA/MF 722/2024 (cadastro) e 827/2024 (PLD/FT)</div><p>Detalham requisitos de cadastro, conta gráfica e prevenção à lavagem das casas de apostas.</p><div class="entra"><b>Onde a kycert entra</b>Cadastro estruturado e registro do que sustentou cada decisão.</div></div><div class="norm reveal"><div class="nlaw">Lei nº 9.613/98 + COAF</div><p>Deveres de PLD/FT e comunicação que passaram a alcançar as Bets.</p><div class="entra"><b>Onde a kycert entra</b>Listas restritivas no fluxo e evidência da avaliação de risco.</div></div></div><p class="fineprint reveal">A kycert estrutura e registra o onboarding; não substitui assessoria jurídica nem dispensa os demais deveres do regulado.</p></div></section>
<section style="padding:64px 0 88px" id="demo"><div class="wrap"><div class="band reveal"><span class="eyebrow on-dark" style="justify-content:center">kycert para apostas / bets</span><h2 class="serif">Mostre à SPA/MF como você identifica.</h2><p>Veja o onboarding de apostadores com trilha auditável, em 30 minutos.</p><div class="cta"><a href="https://api.whatsapp.com/send/?phone=5511977656630&amp;text=Ol%C3%A1%2C+gostaria+de+agendar+uma+demo+da+kycert.&amp;type=phone_number&amp;app_absent=0" class="btn btn-on-dark btn-lg" target="_blank" rel="noopener">Agendar demo</a><a href="/dossie-exemplo" class="btn btn-ghost-dark btn-lg">Ver dossiê de exemplo</a></div></div></div></section>
`;

export default function Page() {
  return (
    <>
      <Nav active="solucoes" />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSONLD }} />
      <div dangerouslySetInnerHTML={{ __html: BODY_HTML }} />
      <Footer />
      <SiteInteractions />
    </>
  );
}
